// <auto-generated />
namespace PharmacyInventory.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class inital1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inital1));
        
        string IMigrationMetadata.Id
        {
            get { return "201805300338330_inital1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
